In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent  # notebooks/ -> project root
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

import pandas as pd

from src.config import (
    PROJECT_ROOT as CONFIG_PROJECT_ROOT,
    DATA_RAW_DIR,
    GEO_LIST_36,
)

from src.data.load_raw import (
    loadHicpIndex,
    loadHicpInflation,
    loadIncomeQuantiles,
    loadEmploymentIndex,
    loadGeoLabels,
    loadCoicopLabels,
)

from src.data.transform_raw import (
    makeHicpIndexLong,
    makeHicpInflationLong,
    makeIncomeQuantilesLong,
    makeEmploymentIndexLong,
)



PROJECT_ROOT, CONFIG_PROJECT_ROOT, DATA_RAW_DIR, len(GEO_LIST_36)

(PosixPath('/Users/princebhanusteta/Documents/Projects/euro-macro-inflation-income'),
 PosixPath('/Users/princebhanusteta/Documents/Projects/euro-macro-inflation-income'),
 PosixPath('/Users/princebhanusteta/Documents/Projects/euro-macro-inflation-income/data_raw'),
 36)

In [2]:
geo = loadGeoLabels()
coicop = loadCoicopLabels()

hicp_index = loadHicpIndex()
hicp_inflation = loadHicpInflation()

print("Geo labels:")
display(geo)

print("COICOP labels:")
display(coicop)

Geo labels:

          geo                                  geo_label
0          AT                                    Austria
1          BE                                    Belgium
2          BG                                   Bulgaria
3          CH                                Switzerland
4          CY                                     Cyprus
5          CZ                                    Czechia
6          DE                                    Germany
7          DK                                    Denmark
8          EA           Euro area (changing composition)
9        EA19       Euro area - 19 countries (2015-2022)
10       EA20       Euro area - 20 countries (from 2023)
11         EE                                    Estonia
12         EL                                     Greece
13         ES                                      Spain
14  EU27_2020  European Union - 27 countries (from 2020)
15         FI                                    Finland
16         FR                                     France
17         HR                                    Croatia
18         HU                                    Hungary
19         IE                                    Ireland
20         IS                                    Iceland
21         IT                                      Italy
22         LT                                  Lithuania
23         LU                                 Luxembourg
24         LV                                     Latvia
25         MT                                      Malta
26         NL                                Netherlands
27         NO                                     Norway
28         PL                                     Poland
29         PT                                   Portugal
30         RO                                    Romania
31         RS                                     Serbia
32         SE                                     Sweden
33         SI                                   Slovenia
34         SK                                   Slovakia
35         UK                             United Kingdom

COICOP labels:

   coicop                                       coicop_label
0    CP00                                     All-items HICP
1    CP01                   Food and non-alcoholic beverages
2    CP02         Alcoholic beverages, tobacco and narcotics
3    CP03                              Clothing and footwear
4    CP04   Housing, water, electricity, gas and other fuels
5    CP05  Furnishings, household equipment and routine h...
6    CP06                                             Health
7    CP07                                          Transport
8    CP08                                     Communications
9    CP09                             Recreation and culture
10   CP10                                          Education
11   CP11                             Restaurants and hotels
12   CP12                   Miscellaneous goods and services

In [3]:
hicp_index_long = makeHicpIndexLong(loadHicpIndex())
hicp_inflation_long = makeHicpInflationLong(loadHicpInflation())
income_long = makeIncomeQuantilesLong(loadIncomeQuantiles())
employment_long = makeEmploymentIndexLong(loadEmploymentIndex())

print("HICP index long:", hicp_index_long.shape)
print("HICP inflation long:", hicp_inflation_long.shape)
print("Income long:", income_long.shape)
print("Employment long:", employment_long.shape)

HICP index long: (145548, 7)
HICP inflation long: (145548, 7)
Income long: (48384, 8)
Employment long: (43200, 9)

In [4]:
# Check
print(hicp_index_long.dtypes)

freq            object
unit            object
coicop          object
geo             object
timeStr         object
hicpIndex      Float64
timeMonth    period[M]
dtype: object

In [5]:
hicp_index_long.head()

  freq unit coicop geo  timeStr  hicpIndex timeMonth
0    M  I15   CP00  AT  2000-01      74.28   2000-01
1    M  I15   CP00  BE  2000-01      72.66   2000-01
2    M  I15   CP00  BG  2000-01      52.49   2000-01
3    M  I15   CP00  CH  2000-01       <NA>   2000-01
4    M  I15   CP00  CY  2000-01      73.63   2000-01

In [6]:
hicp_inflation_long.head()

  freq   unit coicop geo  timeStr  hicpInflation timeMonth
0    M  RCH_A   CP00  AT  2000-01            1.4   2000-01
1    M  RCH_A   CP00  BE  2000-01            0.3   2000-01
2    M  RCH_A   CP00  BG  2000-01            7.0   2000-01
3    M  RCH_A   CP00  CH  2000-01           <NA>   2000-01
4    M  RCH_A   CP00  CY  2000-01            4.4   2000-01

In [7]:
income_long.head()

  freq quantile indic_il currency geo timeStr  incomeValue timeYear
0    A       D1    SHARE      EUR  AT    2000          4.0     2000
1    A       D1    SHARE      EUR  BE    2000          4.0     2000
2    A       D1    SHARE      EUR  BG    2000         <NA>     2000
3    A       D1    SHARE      EUR  CH    2000         <NA>     2000
4    A       D1    SHARE      EUR  CY    2000         <NA>     2000

In [8]:
employment_long.head()

  freq    unit nace_r2 s_adj na_item geo  timeStr  employmentIndex timeQuarter
0    Q  I15_HW       A   SCA  EMP_DC  AT  2000-Q1            158.7      2000Q1
1    Q  I15_HW       A   SCA  EMP_DC  BE  2000-Q1            104.6      2000Q1
2    Q  I15_HW       A   SCA  EMP_DC  BG  2000-Q1            115.7      2000Q1
3    Q  I15_HW       A   SCA  EMP_DC  CH  2000-Q1            107.8      2000Q1
4    Q  I15_HW       A   SCA  EMP_DC  CY  2000-Q1            141.3      2000Q1